### ISSUE TITLE
Неверное отображение времени активности

### ISSUE THREAD

**Issue by MikhailovAlexander** [HSE-Perm-projects-23-24/timetracking-bot#1]
# Отчет об ошибке № 1
**Тестируемая система**: Бот "Ловец времени" https://t.me/timetracking_hse_bot

**Среда обнаружения**: Ubuntu 23.10, Telegram Desktop 5.1.7

**Время обнаружения**: 17.06.24 13:29

**Тестировщик**: MikhailovAlexander 

**Программист**: "не определен"

## Неверно отображается затраченное на активность время
**Статус дефекта**: выявлен.

**Серьезность дефекта**: Значительный (Major).

**Приоритет дефекта**: Высокий (High).

**Подготовительные действия**: Создать активность для отслеживания.

**Воспроизведение дефекта**: Запустить отслеживание активности. Не менее чем через 60 сек. остановить отслеживание активности. Запросить статистику активности за текущий день.

**Фактический результат**: Отображаются только секунды.

**Ожидаемый результат**: Для затраченного время отображаются часы минуты и секунды.

**Подтверждение**: 
Логи сервера показывают что затраченное время 10841

![изображение](https://github.com/HSE-Perm-projects-23-24/timetracking-bot/assets/45492097/ca9527e8-3808-4426-b049-1f16ae4fe860)

Бот выводит только секунды:

![изображение](https://github.com/HSE-Perm-projects-23-24/timetracking-bot/assets/45492097/69e3f74a-67be-4997-be3a-02bb6ea00f27)

**Классификация**: баг отображения данных.

**Комментарии**: Нет.

**Comment by NikiZhu1** [comment]
Баг решён
